name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib scipy pandas tensorflow flake8

    - name: Lint code with flake8
      run: |
        # Ignore some common harmless warnings
        flake8 . --count --show-source --statistics \
          --max-line-length=120 --extend-ignore=E203,W503,F401,F405,F403

    - name: Run unit tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"
